name: build-docker-images

on:
  push:
    tags:
      - v**.**

jobs:
  push_main_to_registry:
    name: Push Docker main-image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: fabianjetzinger/dalle-image-classification
      
      - name: Build and push Main-Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: base-dockerfile
          tags: fabianjetzinger/dalle-image-classification:base-latest

  push_test_to_registry:
    needs: push_main_to_registry
    name: Push Docker test-image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: fabianjetzinger/dalle-image-classification
      
      - name: Build and push Main-Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: test-dockerfile
          tags: fabianjetzinger/dalle-image-classification:test-latest

  call_doctest_workflow:
    needs: push_test_to_registry
    uses: run_doctests.yml@${GITHUB_REF##*/}