name: run-tests

on: [push, workflow_call]

jobs:
  build:

    runs-on: ubuntu-latest
    container: fabianjetzinger/dalle-image-classification:test-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test with pytest
        run: |
          pytest -ra --doctest-modules --junitxml=python-junit.xml --cov --cov-report=xml --cov-report term